#!/bin/bash

######clear all the output file####
sed -i '1,$ d' ../outputFile/jpgRate.txt                  #implement in the pgm2jpg.m file
sed -i '1,$ d' ../outputFile/JPGmsssim.txt                #implement in the ../msssim.m
######For nested loop#######
cd ../Image
a=0
for file in *
do
	cd $file
	for image in *.ppm
	do
	
		NAME=$(echo "$image" | cut -f 1 -d '.')
		echo $file ': ' $image >> ../../outputFile/jpgRate.txt
		echo $file ': ' $image >> ../../outputFile/JPGmsssim.txt

		sz_orig=$(stat -c '%s' $image)
		
		
		cd ../../Code
		
		for quality in 10 30 50 70 90
		#for quality in 10
		do
		a=$((a+1))
			#convert ../Image/$file/$image -quality $quality output$a.jpg
			convert ../Image/$file/$image -quality $quality output.jpg
			
			sz_out2=$(stat -c '%s' output.jpg)

			echo "scale=4 ; $sz_orig / $sz_out2" | bc >> ../outputFile/jpgRate.txt

			#/usr/local/MATLAB/R2016b/bin/matlab -nosplash -nodesktop -r "Smsssim_('../Image/$file/$image','output.jpg','../SaliencyMap/$file/$NAME.pgm');quit;"
			/usr/local/MATLAB/R2016b/bin/matlab -nosplash -nodesktop -r "msssim('../Image/$file/$image','output.jpg');quit;"
		done
		cd ../Image/$file
	done
	cd ..
done			
exit 0
